apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "pods/portforward"]
    verbs: ["get", "list", "watch", "create"]