name: Medalion

on: [push]

env:
  JOB_1_NAME: load_data_to_bronze
  JOB_2_NAME: bronze_to_silver
  JOB_3_NAME: silver_to_gold
  GIT_TOKEN: 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

jobs:
  Release: # jakaś nazwa dla tej sekcjii
    runs-on: self-hosted
    outputs:
      output1: ${{ steps.create_1_job.outputs.groupId }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          repository: kmush12/Medallion
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install kubectl
        shell: bash
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
          sudo install kubectl /usr/local/bin/kubectl
          kubectl version --client=true

      - name: Forward port 9888 to service ilum-core
        run: |
          kubectl port-forward -n default svc/ilum-core 9888:9888 &

#Load data to Bronze

      # zapisać groupId z JSON response na zmienną środowiskowąa
#      - name: Create "Load data to Bronze" Job
#        id: create_1_job
#        run: |
#          curl -X POST "http://localhost:9888/api/v1/group" \
#          -H "Accept: application/json" \
#          -H "Content-Type: multipart/form-data" \
#          -F "name=$JOB_1_NAME" \
#          -F "clusterName=default" \
#          -F "kind=job" \
#          -F "language=python" \
#          -F "scale=1" \
#          -F "pyRequirements=pandas" \
#          -F "pyFiles=@/runner/_work/Medallion/Medallion/Jobs/load_data_to_bronze.py"
#          echo $(jq -r '.groupId')
#          output="groupId=$(jq '.groupId') "
#          >> $GITHUB_OUTPUT
      - name: v2
        id: req
        run: |
          groupId=$(curl -X POST "http://localhost:9888/api/v1/group" \
          -H "Accept: application/json" \
          -H "Content-Type: multipart/form-data" \
          -F "name=$JOB_1_NAME" \
          -F "clusterName=default" \
          -F "kind=job" \
          -F "language=python" \
          -F "scale=1" \
          -F "pyRequirements=pandas" \
          -F "pyFiles=@/runner/_work/Medallion/Medallion/Jobs/load_data_to_bronze.py"
           jq -r '.groupId'); "groupId=$groupId" >> $GITHUB_OUTPUT
        

      - name: Test groupId
        run: |
          echo "GroupId: ${{ steps.req.outputs.groupId }}"
      # ${{ steps.create_1_job.outputs.test }}
      # strzelac Get po joba po nazwie oczekując aż wstaniee
      - name: Wait for the creation of a "Load data to Bronze" job
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 11
          max_attempts: 10
          retry_wait_seconds: 60
          command: |
            curl -X GET "http://localhost:9888/api/v1/group/name/$JOB_1_NAME" \
            -H "Accept: application/json"

      - name: Execute "Load data to Bronze" Job
        #synchroniczny endpoint !!!
        #JOB_ID_1 = steps.run_tests.outputs.
        # jak wyciągnąc groupID z poprzedniego stage i wrzucic w url poniżej
        run: |
          curl "http://ilum.ilum-kacper.piwnica.sofixit.pl/core/api/dev/reactive/truly/group/IDDDDDDDDDDDDDDDDDDDDDDDD/job" \
          -H "Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsIm5iZiI6MTcwNDc5NTg4NSwiaXNzIjoiaHR0cHM6Ly9pbHVtLmNsb3VkIiwiZ3JvdXBzIjpbIkFETUlOIl0sImV4cCI6MTcwNDgyNDY4NSwiaWF0IjoxNzA0Nzk1ODg1fQ.TzggyKUxbNz8OlHqBymFk5_XOgBbGYNxGPkgrXHwl1dE5thJJn1bBimenI5QV93LNMflpd7UzZD2-54mI5-e684NwAmUsOTur-8vvQ5Y5hkVt-95Lgfhpimbt9akuFsXMQrydrwl6ev6ZYkD1NSc5izePta0fIgqJqZ2PaX7e8bAx9o9HPtVp8s27fx3CYbhiaYqtwUYDZ-b_x-Pqwe52OPRkYtHvYTb0vDqq7pXyam-OBMieNyWHVidzbGETIlICFzIohLgBijlBxOGZPi8ud_Bl9ZARKAcWE-WJaa1SaJpU6oH9k2TGUN43BcqHk0eizgSybuK0WOYuLSZcmJiTA" \
          -H "Content-Type: application/json" \
          --data-raw "{"config":{"animals_url":"https://raw.githubusercontent.com/Sofixit/ilum-spark-example/master/medallion-example/animals.csv","owners_url":"https://raw.githubusercontent.com/Sofixit/ilum-spark-example/master/medallion-example/owners.csv","species_url":"https://raw.githubusercontent.com/Sofixit/ilum-spark-example/master/medallion-example/species.csv","animals_bronze_path":"s3a://ilum-files/tables/bronze/animals.csv","owners_bronze_path":"s3a://ilum-files/tables/bronze/owners.csv","species_bronze_path":"s3a://ilum-files/tables/bronze/species.csv"},"clazz":"load_data_to_bronze.RawDataToBronze","type":"interactive_job","cursor":0}"